// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/djordlucas/nine",
        "contact": {
            "name": "Nine",
            "url": "https://github.com/djordlucas/nine"
        },
        "license": {
            "name": "GPL-3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/conversations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all active, idle, and stopped conversations (agent sessions).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "List conversations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListConversationsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new conversation (agent session) with the daemon.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Create a conversation",
                "parameters": [
                    {
                        "description": "conversation config",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateConversationResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns details and context for a specific conversation by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Get conversation details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetConversationResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "conversation not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a conversation and all its event journal data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Delete a conversation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "force flag",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.DeleteConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DeleteConversationResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "conversation not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/context": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the context builder breakdown for a conversation — token usage, sections, tool ranking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Get conversation context",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "verbose flag",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.GetContextRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetContextResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "conversation not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the ordered message and tool-call history for a conversation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Get conversation history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/messages": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a user message to a conversation and returns the agent's response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Send a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "message to send",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "conversation not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/messages/stream": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Opens a Server-Sent Events stream for a conversation, forwarding tool events and response chunks in real time.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Stream conversation messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/replay": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Replays a specific turn in a conversation, re-running the LLM call and tool invocations.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Replay a turn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "turn to replay",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ReplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplayResponse"
                        }
                    },
                    "400": {
                        "description": "missing id or invalid body",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stops a conversation's session, ending the agent worker but preserving the event journal.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Stop a conversation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StopConversationResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "conversation not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/trace": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the detailed LLM call and tool I/O trace for a specific turn in a conversation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Trace a turn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "trace options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.GetTraceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetTraceResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/docs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of available documentation topics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "List documentation topics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListDocsResponse"
                        }
                    }
                }
            }
        },
        "/docs/{topic}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the markdown content for a specific documentation topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get documentation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "documentation topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetDocsResponse"
                        }
                    },
                    "400": {
                        "description": "missing topic",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all goals (active, completed, failed, paused) across all sessions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "List goals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListGoalsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new background goal that spawns a session waking periodically to make progress.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Create a goal",
                "parameters": [
                    {
                        "description": "goal definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateGoalRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateGoalResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns details for a specific goal by ID, including progress and event count.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Get goal details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "goal id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetGoalResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a goal and stops its background session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Delete a goal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "goal id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DeleteGoalResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the API server health status, including daemon connectivity and uptime.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns user notifications, optionally including already-seen ones.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notifications",
                "parameters": [
                    {
                        "description": "include all notifications",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.ListNotificationsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListNotificationsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/plugins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all plugins (builtin and user), their loaded status, tools, and errors.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugins"
                ],
                "summary": "List plugins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListPluginsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/plugins/reload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reloads user plugins from the filesystem, returning the new loaded set.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plugins"
                ],
                "summary": "Reload plugins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReloadPluginsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/attach": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Attaches to an existing conversation session, returning replay events, history, and any pending response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Attach to a session",
                "parameters": [
                    {
                        "description": "session to attach to",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AttachSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AttachSessionResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "session not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/skills": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all available skills (builtin, user, and generated) with names, descriptions, and tags.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skills"
                ],
                "summary": "List skills",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListSkillsResponse"
                        }
                    }
                }
            }
        },
        "/spec": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of available specification topics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "List specification topics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListSpecResponse"
                        }
                    }
                }
            }
        },
        "/spec/{topic}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the markdown content for a specific specification topic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get specification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "specification topic",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetSpecResponse"
                        }
                    },
                    "400": {
                        "description": "missing topic",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the daemon's current status, including sessions, plugins, tools, and memory stats.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get daemon status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StatusResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tools": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all available tools (plugins, sandboxed, and generated).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "List tools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListToolsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tools/reload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reloads sandboxed and generated tools from the filesystem.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Reload tools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReloadToolsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tools/{name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns details for a specific tool by name, including input schema and capabilities.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Get tool details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tool name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetToolResponse"
                        }
                    },
                    "400": {
                        "description": "missing name",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tools/{name}/call": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invokes a tool by name with the given arguments, bypassing the agent loop.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Call a tool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tool name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "tool call arguments",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CallToolRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CallToolResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "tool not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all workflows (running, completed, failed, cancelled) across all sessions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "List workflows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListWorkflowsResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/fail": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks a workflow as failed by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Fail a workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "workflow id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FailWorkflowResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "workflow not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{id}/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancels a running workflow by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflows"
                ],
                "summary": "Stop a workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "workflow id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StopWorkflowResponse"
                        }
                    },
                    "400": {
                        "description": "missing id",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "workflow not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "daemon unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AttachSessionRequest": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                }
            }
        },
        "api.AttachSessionResponse": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "history": {
                    "type": "array",
                    "items": {}
                },
                "instance_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pending_response": {
                    "type": "string"
                },
                "replay_events": {
                    "type": "array",
                    "items": {}
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "api.CallToolRequest": {
            "type": "object",
            "properties": {
                "args": {},
                "live_state": {
                    "type": "boolean"
                }
            }
        },
        "api.CallToolResponse": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "type": "integer"
                },
                "output": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "api.ConversationInfo": {
            "type": "object",
            "properties": {
                "age_seconds": {
                    "type": "integer"
                },
                "attached": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "events_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan_mode": {
                    "type": "string"
                },
                "protected": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.CreateConversationRequest": {
            "type": "object",
            "properties": {
                "interactive": {
                    "type": "boolean"
                }
            }
        },
        "api.CreateConversationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instance_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "api.CreateGoalRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                }
            }
        },
        "api.CreateGoalResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.DeleteConversationRequest": {
            "type": "object",
            "properties": {
                "force": {
                    "type": "boolean"
                }
            }
        },
        "api.DeleteConversationResponse": {
            "type": "object",
            "properties": {
                "deleted_events": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.DeleteGoalResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorDetails": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.ErrorDetails"
                }
            }
        },
        "api.FailWorkflowResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.GetContextRequest": {
            "type": "object",
            "properties": {
                "verbose": {
                    "type": "boolean"
                }
            }
        },
        "api.GetContextResponse": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "context": {}
            }
        },
        "api.GetConversationResponse": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "created_at": {
                    "type": "string"
                },
                "events_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan_mode": {
                    "type": "string"
                },
                "protected": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.GetDocsResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "api.GetGoalResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "events_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "progress": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.GetHistoryResponse": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.HistoryEntry"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.GetSpecResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "api.GetToolResponse": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "generated": {
                    "type": "boolean"
                },
                "input_schema": {},
                "kind": {
                    "type": "string"
                },
                "loaded": {
                    "type": "boolean"
                },
                "manifest_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plugin": {
                    "type": "string"
                }
            }
        },
        "api.GetTraceRequest": {
            "type": "object",
            "properties": {
                "sub_agents": {
                    "type": "boolean"
                },
                "turn": {
                    "type": "integer"
                }
            }
        },
        "api.GetTraceResponse": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "sub_agents": {
                    "type": "boolean"
                },
                "trace": {},
                "turn": {
                    "type": "integer"
                }
            }
        },
        "api.GoalInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "events_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "progress": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "description": "active, completed, failed, paused",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "daemon_connected": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "uptime_seconds": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.HistoryEntry": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tool_input": {},
                "tool_name": {
                    "type": "string"
                },
                "tool_output": {
                    "type": "string"
                },
                "turn_number": {
                    "type": "integer"
                },
                "type": {
                    "description": "user_turn, response, tool_start, tool_end",
                    "type": "string"
                }
            }
        },
        "api.ListConversationsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ConversationInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.ListDocsResponse": {
            "type": "object",
            "properties": {
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.ListGoalsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.GoalInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.ListNotificationsRequest": {
            "type": "object",
            "properties": {
                "all": {
                    "type": "boolean"
                }
            }
        },
        "api.ListNotificationsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Notification"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.ListPluginsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PluginInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.ListSkillsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SkillInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.ListSpecResponse": {
            "type": "object",
            "properties": {
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.ListToolsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ToolInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.ListWorkflowsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.WorkflowInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.MemoryStats": {
            "type": "object",
            "properties": {
                "events_count": {
                    "type": "integer"
                },
                "memories_count": {
                    "type": "integer"
                },
                "workflows_count": {
                    "type": "integer"
                }
            }
        },
        "api.Notification": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "seen": {
                    "type": "boolean"
                },
                "severity": {
                    "description": "info, warning, error",
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.Pagination": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.PluginInfo": {
            "type": "object",
            "properties": {
                "disabled": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "loaded": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "description": "builtin, user",
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.ReloadPluginsResponse": {
            "type": "object",
            "properties": {
                "failed_count": {
                    "type": "integer"
                },
                "loaded_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "plugins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PluginInfo"
                    }
                }
            }
        },
        "api.ReloadToolsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ToolInfo"
                    }
                }
            }
        },
        "api.ReplayRequest": {
            "type": "object",
            "properties": {
                "turn": {
                    "type": "integer"
                }
            }
        },
        "api.ReplayResponse": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "result": {},
                "turn": {
                    "type": "integer"
                }
            }
        },
        "api.SendMessageRequest": {
            "type": "object",
            "properties": {
                "force_think": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "api.SendMessageResponse": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "turn_id": {
                    "type": "string"
                }
            }
        },
        "api.SkillInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "description": "builtin, user, generated",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "active_sessions": {
                    "type": "integer"
                },
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "memory": {
                    "$ref": "#/definitions/api.MemoryStats"
                },
                "plugins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PluginInfo"
                    }
                },
                "status": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ToolInfo"
                    }
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.StopConversationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.StopWorkflowResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.ToolInfo": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "generated": {
                    "type": "boolean"
                },
                "input_schema": {},
                "kind": {
                    "description": "plugin, sandboxed, generated",
                    "type": "string"
                },
                "loaded": {
                    "type": "boolean"
                },
                "manifest_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plugin": {
                    "type": "string"
                }
            }
        },
        "api.WorkflowInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current_step": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "running, completed, failed, cancelled",
                    "type": "string"
                },
                "steps": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication (optional; required only when auth_token is configured)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Nine API",
	Description:      "HTTP/REST API for the Nine AI agent runtime. Provides feature parity with the CLI — conversations, goals, workflows, tools, plugins, skills, and more.\nThe API runs as a separate process that communicates with the daemon via Unix socket.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
