package cli

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"nine/internal/config"
	"nine/internal/protocol"
)

// Processes prints the process roster: everything Nine runs between your
// turns (docs/processes.md).
func (c *CLI) Processes(cfg *config.Config) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	procs, err := cl.ListProcesses()
	if err != nil {
		return fmt.Errorf("list processes: %w", err)
	}
	if len(procs) == 0 {
		fmt.Fprintln(c.Out, "No processes.")
		return nil
	}

	idW, toolW := len("ID"), len("TOOL")
	for _, p := range procs {
		idW, toolW = max(idW, len(p.ID)), max(toolW, len(p.Tool))
	}
	fmt.Fprintf(c.Out, "%-*s %-*s %-5s %-9s %-11s %s\n",
		idW, "ID", toolW, "TOOL", "MODE", "STATE", "TURNS/DAY", "TRIGGER")
	for _, p := range procs {
		fmt.Fprintf(c.Out, "%-*s %-*s %-5s %-9s %-11s %s\n",
			idW, p.ID, toolW, p.Tool, p.Mode, p.State,
			fmt.Sprintf("%d/%d", p.BudgetTurns, p.BudgetTurnsPerDay), processNote(p))
	}
	return nil
}

// processNote is the roster's last column: the trigger, and why a process is
// not running when it is not — the line an operator reads to learn why
// something is quiet.
func processNote(p protocol.ProcessInfo) string {
	switch {
	case p.State == "failing":
		return fmt.Sprintf("%s — %d consecutive failures: %s", p.Trigger, p.Failures, oneLineDetail(p.LastError))
	case p.State == "stopped" && p.StoppedBy == "budget" && p.BudgetResetsAt != "":
		return fmt.Sprintf("%s — paused by its budget until %s", p.Trigger, p.BudgetResetsAt)
	case p.State == "stopped" && p.StoppedBy != "":
		return fmt.Sprintf("%s — stopped by %s", p.Trigger, p.StoppedBy)
	}
	return p.Trigger
}

// ProcessShow prints one process in full, with its recent activity.
func (c *CLI) ProcessShow(cfg *config.Config, id string, lines int) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	p, err := cl.ShowProcess(id, lines)
	if err != nil {
		return err
	}
	row := func(label, value string) {
		if value != "" {
			fmt.Fprintf(c.Out, "  %-13s %s\n", label, value)
		}
	}
	row("id", p.ID)
	row("tool", p.Tool)
	row("mode", p.Mode)
	state := p.State
	if p.StoppedBy != "" {
		state = fmt.Sprintf("%s by %s %s", p.State, p.StoppedBy, p.StoppedAt)
	}
	row("state", state)
	row("trigger", p.Trigger)
	if p.Attached {
		row("session", p.Session+" (attached)")
	} else {
		row("session", p.Session)
	}
	row("role", p.Role)
	row("goal", p.Goal)
	row("report to", p.ReportTo)
	budget := fmt.Sprintf("%d of %d turns, %d of %d tokens today",
		p.BudgetTurns, p.BudgetTurnsPerDay, p.BudgetTokens, p.BudgetTokensPerDay)
	if p.BudgetResetsAt != "" {
		budget += "; resets " + p.BudgetResetsAt
	}
	row("budget", budget)
	if p.Mode == "slice" {
		row("cycles", fmt.Sprintf("%d (%d calls)", p.Cycles, p.Calls))
	}
	if p.Generated {
		row("provenance", "generated by Nine")
	}
	row("last call", p.LastCallAt)
	row("next", p.NextAt)
	if p.Failures > 0 {
		row("failures", fmt.Sprintf("%d consecutive", p.Failures))
	}
	row("last error", oneLineDetail(p.LastError))
	if len(p.Recent) > 0 {
		fmt.Fprintln(c.Out, "  recent")
		printProcessLog(c, p.Recent)
	} else {
		fmt.Fprintln(c.Out, "  (recent activity is kept in memory and empties on restart;")
		fmt.Fprintf(c.Out, "   transitions and reports are in the journal: `nine trace %s`)\n", p.ID)
	}
	return nil
}

func printProcessLog(c *CLI, lines []protocol.ProcessLogLine) {
	for _, e := range lines {
		at := e.At
		if t, err := time.Parse(time.RFC3339, e.At); err == nil {
			at = t.Local().Format("15:04:05")
		}
		detail := ""
		if e.Detail != "" {
			detail = "  " + oneLineDetail(e.Detail)
		}
		fmt.Fprintf(c.Out, "    %s  %-9s%s\n", at, e.Outcome, detail)
	}
}

// ProcessControl starts or stops a process as the operator.
func (c *CLI) ProcessControl(cfg *config.Config, id, action string) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	msg, err := cl.ControlProcess(id, action)
	if err != nil {
		return err
	}
	fmt.Fprintln(c.Out, msg)
	return nil
}

// ProcessSend gives a live process a message from the operator as its next
// trigger.
func (c *CLI) ProcessSend(cfg *config.Config, id, text string) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	msg, err := cl.SendProcess(id, text)
	if err != nil {
		return err
	}
	fmt.Fprintln(c.Out, msg)
	return nil
}

// ToolCall invokes one tool once and prints the whole envelope.
//
// By default it runs against a scratch state namespace, discarded afterwards.
// The trap that avoids is worth knowing about: a test call sharing a live
// standing run's store could overwrite its cursor, and the operator who "just
// tested it" would have silently broken the production run. `--live-state` opts
// in when reproducing a bug needs the real store. Capabilities are never
// sandboxed — a test that cannot make the tool's actual calls tests nothing.
func (c *CLI) ToolCall(cfg *config.Config, tool, argsJSON string, liveState bool) error {
	if argsJSON == "" {
		argsJSON = "{}"
	}
	if !json.Valid([]byte(argsJSON)) {
		return fmt.Errorf("arguments are not valid JSON: %s", argsJSON)
	}
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	out, err := cl.CallTool(tool, json.RawMessage(argsJSON), liveState)
	if err != nil {
		return err
	}
	var pretty map[string]any
	if json.Unmarshal([]byte(out), &pretty) == nil {
		enc, _ := json.MarshalIndent(pretty, "", "  ")
		fmt.Fprintln(c.Out, string(enc))
		return nil
	}
	fmt.Fprintln(c.Out, out)
	return nil
}

// dialDaemon connects to a running daemon for inspection, reporting the "none
// running" case once rather than at every call site.
//
// Deliberately not CLI.connect, which starts a daemon if none is up. Reading a
// process's status should not bring a daemon into existence — the honest
// answer to "what is running" when nothing is running is "nothing".
func (c *CLI) dialDaemon(cfg *config.Config) (*protocol.Client, func(), error) {
	sock := cfg.SocketPath()
	if !protocol.CanConnect(sock) {
		fmt.Fprintln(c.Out, "no daemon running; start one with `nine daemon`")
		return nil, func() {}, nil
	}
	cl, err := protocol.Connect(sock)
	if err != nil {
		return nil, func() {}, fmt.Errorf("connect: %w", err)
	}
	return cl, func() { cl.Close() }, nil //nolint:errcheck
}

func oneLineDetail(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	if len(s) > 100 {
		s = s[:100] + "…"
	}
	return s
}
