package cli

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"nine/internal/config"
	"nine/internal/protocol"
)

// Standing prints the standing-run roster: tools the daemon runs indefinitely
// on their own cadence.
func (c *CLI) Standing(cfg *config.Config) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	runs, err := cl.ListStanding()
	if err != nil {
		return fmt.Errorf("list standing tools: %w", err)
	}
	if len(runs) == 0 {
		fmt.Fprintln(c.Out, "No standing tools.")
		return nil
	}

	idW := len("ID")
	for _, r := range runs {
		if len(r.ID) > idW {
			idW = len(r.ID)
		}
	}
	fmt.Fprintf(c.Out, "%-*s %-14s %-9s %7s %7s  %s\n",
		idW, "ID", "TOOL", "STATE", "CYCLES", "CALLS", "TRIGGER")
	for _, r := range runs {
		note := r.Trigger
		if r.State == "failing" {
			// The state alone does not say what is wrong, and this is the line an
			// operator reads when they want to know why something is quiet.
			note = fmt.Sprintf("%s — %d consecutive failures: %s",
				r.Trigger, r.Failures, oneLineDetail(r.LastError))
		}
		fmt.Fprintf(c.Out, "%-*s %-14s %-9s %7d %7d  %s\n",
			idW, r.ID, r.Tool, r.State, r.Cycles, r.Calls, note)
	}
	return nil
}

// StandingShow prints one standing run in full, with its recent activity.
func (c *CLI) StandingShow(cfg *config.Config, id string, lines int) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	r, err := cl.ShowStanding(id, lines)
	if err != nil {
		return err
	}
	fmt.Fprintf(c.Out, "  id            %s\n", r.ID)
	fmt.Fprintf(c.Out, "  tool          %s\n", r.Tool)
	fmt.Fprintf(c.Out, "  state         %s\n", r.State)
	fmt.Fprintf(c.Out, "  trigger       %s\n", r.Trigger)
	fmt.Fprintf(c.Out, "  cycles        %d (%d calls)\n", r.Cycles, r.Calls)
	if r.Generated {
		fmt.Fprintf(c.Out, "  provenance    generated by Nine\n")
	}
	if r.LastCallAt != "" {
		fmt.Fprintf(c.Out, "  last call     %s\n", r.LastCallAt)
	}
	if r.NextAt != "" {
		fmt.Fprintf(c.Out, "  next call     %s\n", r.NextAt)
	}
	if r.Failures > 0 {
		fmt.Fprintf(c.Out, "  failures      %d consecutive\n", r.Failures)
	}
	if r.LastError != "" {
		fmt.Fprintf(c.Out, "  last error    %s\n", oneLineDetail(r.LastError))
	}
	if len(r.Recent) > 0 {
		fmt.Fprintln(c.Out, "  recent")
		printStandingLog(c, r.Recent)
	}
	return nil
}

// StandingLogs prints a standing run's recent activity.
//
// It reads a bounded in-memory ring rather than the journal, deliberately: a
// tool on a ten-second cadence makes thousands of calls a day, and none of them
// are journal events (only its transitions and its output are). So this is
// "what has it been doing lately", and it does not survive a restart.
func (c *CLI) StandingLogs(cfg *config.Config, id string, lines int) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	r, err := cl.ShowStanding(id, lines)
	if err != nil {
		return err
	}
	if len(r.Recent) == 0 {
		fmt.Fprintf(c.Out, "No recent activity for %s. (This buffer is in memory and empties on restart;\n"+
			"its transitions and output are in the journal — try `nine trace %s`.)\n", r.ID, r.ID)
		return nil
	}
	printStandingLog(c, r.Recent)
	return nil
}

func printStandingLog(c *CLI, lines []protocol.StandingLogLine) {
	for _, e := range lines {
		at := e.At
		if t, err := time.Parse(time.RFC3339, e.At); err == nil {
			at = t.Local().Format("15:04:05")
		}
		detail := ""
		if e.Detail != "" {
			detail = "  " + oneLineDetail(e.Detail)
		}
		fmt.Fprintf(c.Out, "    %s  %-9s%s\n", at, e.Outcome, detail)
	}
}

// StandingControl stops or starts a standing run.
func (c *CLI) StandingControl(cfg *config.Config, id, action string) error {
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	msg, err := cl.ControlStanding(id, action)
	if err != nil {
		return err
	}
	fmt.Fprintln(c.Out, msg)
	return nil
}

// ToolCall invokes one tool once and prints the whole envelope.
//
// By default it runs against a scratch state namespace, discarded afterwards.
// The trap that avoids is worth knowing about: a test call sharing a live
// standing run's store could overwrite its cursor, and the operator who "just
// tested it" would have silently broken the production run. `--live-state` opts
// in when reproducing a bug needs the real store. Capabilities are never
// sandboxed — a test that cannot make the tool's actual calls tests nothing.
func (c *CLI) ToolCall(cfg *config.Config, tool, argsJSON string, liveState bool) error {
	if argsJSON == "" {
		argsJSON = "{}"
	}
	if !json.Valid([]byte(argsJSON)) {
		return fmt.Errorf("arguments are not valid JSON: %s", argsJSON)
	}
	cl, done, err := c.dialDaemon(cfg)
	if err != nil || cl == nil {
		return err
	}
	defer done()

	out, err := cl.CallTool(tool, json.RawMessage(argsJSON), liveState)
	if err != nil {
		return err
	}
	var pretty map[string]any
	if json.Unmarshal([]byte(out), &pretty) == nil {
		enc, _ := json.MarshalIndent(pretty, "", "  ")
		fmt.Fprintln(c.Out, string(enc))
		return nil
	}
	fmt.Fprintln(c.Out, out)
	return nil
}

// dialDaemon connects to a running daemon for inspection, reporting the "none
// running" case once rather than at every call site.
//
// Deliberately not CLI.connect, which starts a daemon if none is up. Reading a
// standing tool's status should not bring a daemon into existence — the honest
// answer to "what is running" when nothing is running is "nothing".
func (c *CLI) dialDaemon(cfg *config.Config) (*protocol.Client, func(), error) {
	sock := cfg.SocketPath()
	if !protocol.CanConnect(sock) {
		fmt.Fprintln(c.Out, "no daemon running; start one with `nine daemon`")
		return nil, func() {}, nil
	}
	cl, err := protocol.Connect(sock)
	if err != nil {
		return nil, func() {}, fmt.Errorf("connect: %w", err)
	}
	return cl, func() { cl.Close() }, nil //nolint:errcheck
}

func oneLineDetail(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	if len(s) > 100 {
		s = s[:100] + "…"
	}
	return s
}
